/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist;

import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class TelaToDoList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaToDoList.class.getName());

    DefaultTableModel model;
    
    private static final String CONCLUIDA = "concluída";
    private static final String NAO_CONCLUIDA = "Não concluída";
    
    private final ArrayList<String> tarefas = new ArrayList<>();
     private final ArrayList<String> tarefasFiltradas = new ArrayList<>();
    /**
     * Creates new form TelaToDoList
     */
    public TelaToDoList() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) jTableTarefas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDescricaoTarefa = new javax.swing.JTextField();
        jButton1AdicionarTarefa = new javax.swing.JButton();
        jComboBoxFiltroStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jButtonConcluirTarefa = new javax.swing.JButton();
        jButtonRemoverTarefa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldDescricaoTarefa.addActionListener(this::jTextFieldDescricaoTarefaActionPerformed);

        jButton1AdicionarTarefa.setText("Adicionar");
        jButton1AdicionarTarefa.addActionListener(this::jButton1AdicionarTarefaActionPerformed);

        jComboBoxFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Concluído", "Não concluído" }));

        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefa", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableTarefas);

        jButtonConcluirTarefa.setText("Concluir");
        jButtonConcluirTarefa.addActionListener(this::jButtonConcluirTarefaActionPerformed);

        jButtonRemoverTarefa.setText("Remover");
        jButtonRemoverTarefa.addActionListener(this::jButtonRemoverTarefaActionPerformed);

        jLabel1.setText("Adicione a atividade que deseja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDescricaoTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1AdicionarTarefa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonConcluirTarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonRemoverTarefa))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1AdicionarTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcluirTarefa)
                    .addComponent(jButtonRemoverTarefa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescricaoTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoTarefaActionPerformed

    private void jButtonConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirTarefaActionPerformed
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
        if(linhaSelecionada < 0){
        JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi selecionada!");
        return;
        }
        
        String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
        
        int indiceTarefaSelecinada = tarefas.indexOf(tarefaSelecionada);
        
        String[] dados = tarefas.get(indiceTarefaSelecinada).split(";");
        
        tarefas.set(indiceTarefaSelecinada, dados[0] + ";" + CONCLUIDA);
        
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jButtonConcluirTarefaActionPerformed

    private void jButton1AdicionarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AdicionarTarefaActionPerformed
    if (jTextFieldDescricaoTarefa.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "A descrição da tarefa não,pode ser vazia");
        return;
        }   
    
     if(hasTarefaRepetida(jTextFieldDescricaoTarefa.getText())){
         JOptionPane.showMessageDialog(null, "A tarefa " + jTextFieldDescricaoTarefa.getText() + " já existe");
         return;
     }   
     
     tarefas.add(jTextFieldDescricaoTarefa.getText() + ";" + NAO_CONCLUIDA);
     
     preencherTabela();
     
     jTextFieldDescricaoTarefa.setText("");
    }//GEN-LAST:event_jButton1AdicionarTarefaActionPerformed

    private void jButtonRemoverTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverTarefaActionPerformed
    int linhaSelecionada = jTableTarefas.getSelectedRow();
    
    if(linhaSelecionada < 0){
      JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi selecionada!");
      return;
       }
    
    int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a tarefa");
    
    String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
    
    int indiceTarefaSelecionada = tarefas.indexOf(tarefaSelecionada);
    
    if(opcao == JOptionPane.YES_OPTION){
        tarefas.remove(indiceTarefaSelecionada);
        preencherTabela();
      }
    
    filtrarTabela();
    
    preencherTabela();
    }//GEN-LAST:event_jButtonRemoverTarefaActionPerformed

    private void filtrarTabela(){
        int opcao = jComboBoxFiltroStatus.getSelectedIndex();
        tarefasFiltradas.clear();
        
        String[] dados;
        
        for(String tarefa : tarefas){
            dados = tarefa.split(";");
            
            switch (opcao) {
                case 0:
                   tarefasFiltradas.add(tarefa);
                    break;
                case 1:
                    if(dados[1].equals(CONCLUIDA)){
                       tarefasFiltradas.add(tarefa);
                    }
                    
                    break;
                case 2:
                    if (dados[1].equals(NAO_CONCLUIDA)){
                        tarefasFiltradas.add(tarefa);
                }
                    break;
                default:
                    throw new AssertionError();
            }
            
        }
    }
    
    private String recuperarTarefa(int indiceTarefa){
        if (jComboBoxFiltroStatus.getSelectedIndex() > 0){
            return tarefasFiltradas.get(indiceTarefa);
        }else{
            return tarefas.get(indiceTarefa);
        }
    }
           
    public boolean hasTarefaRepetida(String novaTarefa) {
        for (String tarefa : tarefas) {
            String dados[] = tarefa.split(";");
            
            if (novaTarefa.toLowerCase().equals(dados[0].toLowerCase())){
                return true;
            }
        }
        
        return false;
    }
    
    private void preencherTabela(){
        ArrayList<String> listaTarefas;
        
        if(jComboBoxFiltroStatus.getSelectedIndex() >0){
            listaTarefas = tarefasFiltradas;
        }else{
            listaTarefas = tarefas;
        }
        
        model.setRowCount(0);
        
        for (String tarefa : listaTarefas){
            String[] dados = tarefa.split(";");
            
            model.addRow(new Object[]{
            dados[0],
            dados[1]
        });
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaToDoList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1AdicionarTarefa;
    private javax.swing.JButton jButtonConcluirTarefa;
    private javax.swing.JButton jButtonRemoverTarefa;
    private javax.swing.JComboBox<String> jComboBoxFiltroStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextField jTextFieldDescricaoTarefa;
    // End of variables declaration//GEN-END:variables
}
